version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: main
    commit-message:
      prefix: ":seedling:"
      include: scope
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: main
    commit-message:
      prefix: ":seedling:"
      include: scope
    groups:
      all-github-actions:
        patterns: ["*"]
