version: 2
project_name: routest
release:
  github:
    owner: mikejoh
    name: routest
  name_template: 'v{{ .Tag }}'
builds:
  - id: routest
    targets:
      - linux_amd64_v1
      - darwin_amd64_v1
      - windows_amd64_v1
    dir: .
    main: ./cmd/routest/
    binary: routest
    builder: go
    gobinary: go
    command: build
    ldflags:
      - -s -w -X=github.com/mikejoh/routest/internal/buildinfo.Version={{ .Version }} -X=github.com/mikejoh/routest/internal/buildinfo.Name=routest -X=github.com/mikejoh/routest/internal/buildinfo.GitSHA={{ .Commit }}
dist: ./build
