version: 2
project_name: routest
release:
  github:
    owner: mikejoh
    name: routest
  name_template: 'v{{ .Tag }}'
builds:
  - id: routest
    targets:
      - linux_amd64_v1
      - darwin_amd64_v1
      - windows_amd64_v1
    dir: .
    main: ./cmd/routest/
    binary: routest
    ldflags:
      - -s -w -X=github.com/mikejoh/routest/internal/buildinfo.Version={{ .Version }} -X=github.com/mikejoh/routest/internal/buildinfo.Name=routest -X=github.com/mikejoh/routest/internal/buildinfo.GitSHA={{ .Commit }}
homebrew_casks:
  - name: routest
    repository:
      owner: mikejoh
      name: homebrew-routest
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Casks
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "chore: update routest cask to {{ .Tag }}"
    homepage: "https://github.com/mikejoh/routest"
    description: "Test your Alertmanager route configuration"
    binaries:
      - routest

dist: ./build
